name: online_market
description: A Platform for both buyers and sellers to interact buy purchasing and selling items.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  unicons: ^2.1.0
  eva_icons_flutter: ^3.1.0
  font_awesome_flutter: ^10.1.0
  change_app_package_name: ^1.0.0
  carousel_slider: ^4.1.1
  firebase_auth: ^3.0.1
  firebase_core: ^1.17.0
  firebase_storage: ^10.0.1
  cloud_firestore: ^3.1.6
  cached_network_image: ^3.2.0
  provider: ^6.0.2
  google_nav_bar: ^5.0.5
  intl_phone_field: ^3.0.1
  image_picker: ^0.8.5+3



  progress_dialog:
    git:
      url: https://github.com/mostafaAbdelazim/progress_dialog.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg