name: online_market
description: A Platform for both buyers and sellers to interact buy purchasing
  and selling items.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  another_flushbar: ^1.12.29
  auto_route: ^5.0.4
  cached_network_image: ^3.2.0
  carousel_slider: ^4.1.1
  change_app_package_name: ^1.0.0
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.2
  dropdown_button2: ^1.6.0
  equatable: ^2.0.5
  eva_icons_flutter: ^3.1.0
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  fluttertoast: ^8.1.2
  font_awesome_flutter: ^10.1.0
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  google_nav_bar: ^5.0.5
  http: ^0.13.4
  image_cropper: ^3.0.1
  image_picker: ^0.8.5+3
  intl_phone_field: ^3.0.1
  localstorage: ^4.0.0+1
  mime: ^1.0.4
  path_provider: ^2.0.11
  progress_dialog:
    git:
      url: https://github.com/mostafaAbdelazim/progress_dialog.git
  provider: ^6.0.2
  shared_preferences: ^2.0.15
  unicons: ^2.1.0

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: null
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.0


  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
assets:
  - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/agricma.png"