// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiC0PB6h6WwzrvSzJpfUgbtRQCtGPiaes',
    appId: '1:652439904406:web:af71fbc673be776e2ae2b7',
    messagingSenderId: '652439904406',
    projectId: 'emarket-e9032',
    authDomain: 'emarket-e9032.firebaseapp.com',
    databaseURL: 'https://emarket-e9032-default-rtdb.firebaseio.com',
    storageBucket: 'emarket-e9032.appspot.com',
    measurementId: 'G-KYN1EE88LE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZiBlM4N4Hu1vN9v3D336ZVg_1KU7jkUI',
    appId: '1:652439904406:android:52fd3b741db855e22ae2b7',
    messagingSenderId: '652439904406',
    projectId: 'emarket-e9032',
    databaseURL: 'https://emarket-e9032-default-rtdb.firebaseio.com',
    storageBucket: 'emarket-e9032.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1R6q__Yw6qud21z9KHknm58wrHBDJOOk',
    appId: '1:652439904406:ios:cddc5650ddfe34432ae2b7',
    messagingSenderId: '652439904406',
    projectId: 'emarket-e9032',
    databaseURL: 'https://emarket-e9032-default-rtdb.firebaseio.com',
    storageBucket: 'emarket-e9032.appspot.com',
    iosClientId: '652439904406-dsqtkeetjp9j89js2j46sd5brs8i5n0a.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineMarket',
  );
}
