// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhxem6kqETJUAzvU_WdrlYvm1581IAc3A',
    appId: '1:201804217099:web:dfc9518dc4f8a24e03000e',
    messagingSenderId: '201804217099',
    projectId: 'emarket-3689e',
    authDomain: 'emarket-3689e.firebaseapp.com',
    storageBucket: 'emarket-3689e.appspot.com',
    measurementId: 'G-F6R9C8YQ3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6oQDSIuql8pN3LxM3gznbxf_PK4GTOVc',
    appId: '1:201804217099:android:1e227a18554028a703000e',
    messagingSenderId: '201804217099',
    projectId: 'emarket-3689e',
    storageBucket: 'emarket-3689e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBynzPjUcUxde1Dz806tJ1yZUjxBl-2NOE',
    appId: '1:201804217099:ios:654994290ec5c9e803000e',
    messagingSenderId: '201804217099',
    projectId: 'emarket-3689e',
    storageBucket: 'emarket-3689e.appspot.com',
    iosClientId: '201804217099-pj4enm9pol6blasfm5h4to5kuih6g04d.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineMarket',
  );
}
